### ISSUE TITLE
How Pub/Sub works

### ISSUE THREAD

**Issue by prakashchoudhary07** [Real-Dev-Squad/notification-service#3]

**Comment by vikhyat187** [comment]
[DRAFT]
- Pub / Sub stands for Publisher / Subscriber pattern.
- Its used to decouple services, make communication async.
<img width="748" alt="Screenshot 2023-01-11 at 12 23 38 AM" src="https://user-images.githubusercontent.com/52795644/211637289-4ee69202-00f2-416c-b203-bd909f834216.png">

> Publishers communicate asynchronously with subscribers by producing and sending a message to a topic, which is a logical access point and communication channel. Subscribers (web servers, email addresses, Amazon SQS queues, Lambda functions) consume or receive the message or notification over one of the supported protocols (Amazon SQS, HTTP/S, email, SMS, AWS Lambda) when they are subscribed to the topic.

[Sample code (AWS) for creating topics](https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javascript/example_code/sns/sns_createtopic.js)

[Sample code SNS](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sns-examples.html)

- How can it be integrated with RDS repo
- Procedure to implement it
- How will the topic and response look like.
- In house/ managed pub sub service?

**Comment by vikhyat187** [comment]
Kafka vs Rabbit MQ [DRAFT]



<img width="1289" alt="Screenshot 2023-02-11 at 10 23 12 PM" src="https://user-images.githubusercontent.com/52795644/218270530-6a5e4938-18c3-4ca3-b779-f81fe4743d17.png">

While deciding between Apache Kafka vs RabbitMQ, it is to be noted that unlike Kafka, which can keep a large amount of data with minimum overhead, RabbitMQ queues are only quicker when they’re empty.




https://medium.com/analytics-vidhya/apache-kafka-architecture-getting-started-with-apache-kafka-771d69ac6cef
https://hevodata.com/learn/kafka-vs-rabbitmq/
https://blog.logrocket.com/kafka-vs-rabbitmq-comparing-node-js-message-brokers/
https://www.notificationapi.com/blog/notification-service-design-with-architectural-diagrams
https://tanzu.vmware.com/developer/blog/understanding-the-differences-between-rabbitmq-vs-kafka/
https://www.cloudamqp.com/blog/rabbitmq-use-cases-explaining-message-queues-and-when-to-use-them.html
[About Kafka](youtube.com/watch?v=LN_HcJVbySw&ab_channel=HusseinNasser)
https://www.confluent.io/blog/kafka-fastest-messaging-system/

-------------------------------------------
| Parameters | Kafka | RabbitMQ | SNS + SQS | 
| ----------- | -------- | ------- | ---------- |
| Event microservices | supports | supports | supports | 
| Stream processing | supports | supports (need to explore this) | not sure on this | 
| Scale | Will be easily scalable | will be hard to scale | scalable as managed service | 
| Retries | Will not support in house retries need to create explicitly | supports (need to explore on this) | supports dead letter queue | 
| Fifo | Not sure | Not sure | Yes | 
| Delivery latency | Less | not sure | Compared to kafka more | 
| Cost |  less | will be more on scale | compared to kafka more | 
| Internal working | Stores in disk | stores **In memory** | not sure | 
| mechanism | poll based | push based | not sure |

**Comment by vikhyat187** [comment]
As per discussion with @prakashchoudhary07, we are going with Kafka.
